on: [push]
steps:
- name: Set up R
  uses: r-lib/actions/setup-r
  with:
    r-version: [3.6.1]
- name: Set up Python
  uses: actions/setup-python@v2
  with:
    python-version: '3.7.10'
- name: Install dependencies
  run: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
- name: Test with pytest
  run: |
    pip install pytest
    pip install pytest-cov
    pytest ./robusta/groupwise/test_groupwise.py
    pytest ./robusta/regressions/test_regressions.py