# TODO - change to run both on MacOS and Windows, currently only triens ubuntu
# TODO - check how to cache dependencies

on: [ push ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.7.10 ]
        os: [ ubuntu-latest ]
    #        include:
    #          - os: ubuntu-latest
    #            path: ~/.cache/pip
    #          - os: macos-latest
    #            path: ~/Library/Caches/pip
    #          - os: windows-latest
    #            path: ~\AppData\Local\pip\Cache

    runs-on: ${{matrix.os}}
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@master
        with:
          r-version: 3.6.1

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/checkout@v2
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/checkout@v1

      - uses: actions/setup-python@v2

      - uses: syphar/restore-virtualenv@v1
        id: cache-virtualenv
        with:
          requirement_files: requirements.txt  # this is optional

      - uses: syphar/restore-pip-download-cache@v1
        if: steps.cache-virtualenv.outputs.cache-hit != 'true'

      # the package installation will only be executed when the
      # requirements-files have changed.
      - run: pip install -r requirements.txt
        if: steps.cache-virtualenv.outputs.cache-hit != 'true'

      - name: Install package
        run: |
          python setup.py install

      - name: Run tests
        run: |
          pytest ./robusta/groupwise/test_groupwise.py
          pytest ./robusta/regressions/test_regressions.py
          pytest ./robusta/regressions/test_correlations.py
