# TODO - change to run both on MacOS and Windows, currently only triens ubuntu
# TODO - check how to cache dependencies

on: [ push ]

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.7.10]

    runs-on: ${{matrix.os}}
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@master
        with:
          r-version: 3.6.1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/checkout@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install package
        run: |
          python setup.py install
      - name: Run tests
        run: |
          pytest ./robusta/groupwise/test_groupwise.py
          pytest ./robusta/regressions/test_regressions.py
          pytest ./robusta/regressions/test_correlations.py
