# TODO - change to run both on MacOS and Windows, currently only triens ubuntu
# TODO - check how to cache dependencies

on: [ push ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.7.10 ]
        os: [ ubuntu-latest ]
    #        include:
    #          - os: ubuntu-latest
    #            path: ~/.cache/pip
    #          - os: macos-latest
    #            path: ~/Library/Caches/pip
    #          - os: windows-latest
    #            path: ~\AppData\Local\pip\Cache

    runs-on: ${{matrix.os}}
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@master
        with:
          r-version: 3.6.1

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/checkout@v2
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/checkout@v1

      - uses: actions/setup-python@v2

      - run: pip install -r requirements.txt

      - name: Install package
        run: |
          python setup.py install

      - name: Import robusta
        run: |
          python -c "import robusta as rst"

      #      - name: Run tests
      #        run: |
      #          pytest ./robusta/tests
      #          pytest ./robusta/groupwise/tests
      #          pytest ./robusta/regressions/tests/test_regressions.py
      #          pytest ./robusta/correlations/test/test_correlations.py

      - name: Build docs
        uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "docs/"
          build-command: "sphinx-build source build"