# TODO - change to run both on MacOS and Windows, currently only triens ubuntu
# TODO - check how to cache dependencies

on: [ push ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.7.10 ]
        os: [ ubuntu-latest]
        include:
          - os: ubuntu-latest
            path: ~/.cache/pip
          - os: macos-latest
            path: ~/Library/Caches/pip
          - os: windows-latest
            path: ~\AppData\Local\pip\Cache

    runs-on: ${{matrix.os}}
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@master
        with:
          r-version: 3.6.1

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/checkout@v2
        with:
          python-version: ${{ matrix.python-version }}

#      - uses: actions/cache@master
#        id: cache
#        with:
#          path: ${{ env.pythonLocation}}/lib/python3.7/site-packages/*
#          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
#          restore-keys: |
#            ${{ runner.os }}-pip-
#            ${{ runner.os }}-

      - name: Install Dependencies
#        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          echo "Installing dependencies and caching them."
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt

      - name: Install package
        run: |
          python setup.py install
      - name: Run tests
        run: |
          pytest ./robusta/groupwise/test_groupwise.py
          pytest ./robusta/regressions/test_regressions.py
          pytest ./robusta/regressions/test_correlations.py
