on: [ push ]

jobs:
  installations:
    name: install Python / R
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7.10'
      - name: Set up R
        uses: r-lib/actions/setup-r@master
        with:
          r-version: 3.6.1
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      - name: Install package
        run: |
            python setup.py install
  tests:
    name: Test using PyTest
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: |
            pytest ./robusta/groupwise/test_groupwise.py
            pytest ./robusta/regressions/test_regressions.py